import Card from "./Card";
import Content from "./Content";
import DrawerLeft from "./DrawerLeft";
import Footer from "./Footer";
import Modal from "./Modal";
import Navbar from "./Navbar";
import Pagination from "./Pagination";
import FreelancerRqt from "./FreelancerRqt";
import MessageModal from "./MessageModal";
import Message from "./Messages";
import Fcard from "./Fcard";
import Range from "./Range";
import Uprofile from "./Uprofile";
import Updateprof from "./Updateprof";
import Fprofile from "./Fprofile";
import FupdateProf from "./FupdateProf";
export { Card, Content, DrawerLeft, Footer, Modal, Navbar, Pagination, FreelancerRqt, MessageModal,Message,Fcard,Range,Uprofile,Updateprof,Fprofile,FupdateProf};